[package]
name = "gameterm-visual"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
publish = false

[dependencies]
image.workspace = true
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
k9.workspace = true
tempfile.workspace = true
