#!/usr/bin/env python3
"""Classify every source file as generated / vendored / test / owned and report
true LOC per crate.

The point is legibility: a fork inherits a lot of code, and raw LOC is
misleading because much of it is machine-generated tables or vendored upstream
code that carries ~zero maintenance burden. This script makes the *owned* surface
(the part a human actually maintains) explicit, so "is this repo maintainable?"
is answerable from data, not vibes.

Re-run after structural changes:  python3 ci/repo-index.py
Markdown table for the index doc:  python3 ci/repo-index.py --md
"""
from __future__ import annotations
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories that are never "owned" maintenance surface.
SKIP_DIRS = {".git", "target", "node_modules"}
VENDORED_TOP = {"deps", "vendor"}  # upstream code vendored in-tree
# Untracked local release artifacts (extracted zips); not part of the repo.
CRUFT_PREFIX = ("GameTerm-macos-",)

SOURCE_EXTS = {".rs", ".lua", ".py", ".sh"}

# Header markers that identify machine-generated files.
GEN_MARKERS = (
    "@generated",
    "generated by",
    "this file was generated",
    "do not edit",
    "auto-generated",
    "automatically generated",
    "code generated",
)
# Known generated files that may lack an obvious header.
GEN_NAMES = {
    "unicode_names.rs",
    "emoji_variation.rs",
    "nerdfonts_data.rs",
    "widechar_width.rs",
}


def classify(path: str, rel: str) -> str:
    top = rel.split(os.sep, 1)[0]
    if top in VENDORED_TOP:
        return "vendored"
    name = os.path.basename(path)
    if name in GEN_NAMES:
        return "generated"
    # test code: tests/ dirs or *_test.rs / tests.rs
    parts = rel.split(os.sep)
    if "tests" in parts or name == "tests.rs" or name.endswith("_test.rs"):
        return "test"
    try:
        with open(path, "r", errors="ignore") as fh:
            head = fh.read(2000).lower()
    except OSError:
        return "owned"
    if any(m in head for m in GEN_MARKERS):
        return "generated"
    return "owned"


def loc(path: str) -> int:
    try:
        with open(path, "rb") as fh:
            return sum(1 for _ in fh)
    except OSError:
        return 0


def main() -> int:
    md = "--md" in sys.argv
    # crate -> {category: loc}
    crates: dict[str, dict[str, int]] = {}
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [
            d for d in dirnames
            if d not in SKIP_DIRS
            and not d.startswith(".")  # .cache, .cargo, .git, .github, …
            and not d.startswith(CRUFT_PREFIX)
        ]
        for fn in filenames:
            ext = os.path.splitext(fn)[1]
            if ext not in SOURCE_EXTS:
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ROOT)
            top = rel.split(os.sep, 1)[0]
            if top.startswith(CRUFT_PREFIX) or top in SKIP_DIRS:
                continue
            cat = classify(full, rel)
            n = loc(full)
            crates.setdefault(top, {}).setdefault(cat, 0)
            crates[top][cat] += n

    cats = ("owned", "generated", "test", "vendored")
    rows = []
    for crate, d in crates.items():
        rows.append((crate, {c: d.get(c, 0) for c in cats}))
    rows.sort(key=lambda r: r[1]["owned"], reverse=True)

    totals = {c: sum(d[c] for _, d in rows) for c in cats}
    grand = sum(totals.values())

    if md:
        print("| crate / folder | owned | generated | test | vendored |")
        print("|---|--:|--:|--:|--:|")
        for crate, d in rows:
            if sum(d.values()) == 0:
                continue
            print(f"| `{crate}` | {d['owned']:,} | {d['generated']:,} | {d['test']:,} | {d['vendored']:,} |")
        print(f"| **TOTAL** | **{totals['owned']:,}** | **{totals['generated']:,}** | **{totals['test']:,}** | **{totals['vendored']:,}** |")
    else:
        print(f"{'crate/folder':28} {'owned':>9} {'generated':>10} {'test':>8} {'vendored':>9}")
        for crate, d in rows:
            if sum(d.values()) == 0:
                continue
            print(f"{crate:28} {d['owned']:>9,} {d['generated']:>10,} {d['test']:>8,} {d['vendored']:>9,}")
        print("-" * 70)
        print(f"{'TOTAL':28} {totals['owned']:>9,} {totals['generated']:>10,} {totals['test']:>8,} {totals['vendored']:>9,}")
        owned_pct = 100 * totals["owned"] / grand if grand else 0
        print(f"\nTotal source lines: {grand:,}")
        print(f"Owned (hand-maintained): {totals['owned']:,} ({owned_pct:.0f}%)")
        print(f"Generated: {totals['generated']:,}  |  Test: {totals['test']:,}  |  Vendored: {totals['vendored']:,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
